version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4306:4306'
    environment:
      - MONGODB_URI=${MONGODB_URI}

      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - REDIRECT_URI=${REDIRECT_URI}

      - SECRET_KEY=${SECRET_KEY}
